name: PushPlus Notification

on:
  schedule:
    - cron: '0 12 * * 0' # 每周五7点执行
  push:
    branches:
      - main

jobs:
  pushplus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # 使用 Python 3.x 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # 安装 requests 库

    - name: Run PushPlus script
      run: |
        python send_message.py
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} # 从 GitHub Secrets 中获取 PushPlus Token